// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI only (migrate/studio/generate) — the app's own PrismaClient
    // (src/lib/prisma.ts) builds its adapter straight from DATABASE_URL
    // itself and never reads this file, so this doesn't affect runtime.
    // Migrations need the *unpooled* connection: `migrate deploy` takes a
    // Postgres advisory lock, which Neon's pooled/PgBouncer endpoint doesn't
    // reliably support and can hang or time out on.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
